source 'https://rubygems.org'
ruby '1.9.3'

gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-assetpack',
  :require => 'sinatra/assetpack'
gem 'sinatra-advanced-routes',
  :require => 'sinatra/advanced_routes'
gem 'sinatra-export'
gem 'rake'
gem 'rack'
gem 'sass'

group :deploy do
  gem 'capistrano'
  gem 'capistrano-s3'
end